Debug_MapScripts::
	.byte 0

FameCheckerFull::
	famechecker FAMECHECKER_BROCK, 0
	famechecker FAMECHECKER_BROCK, 1
	famechecker FAMECHECKER_BROCK, 2
	famechecker FAMECHECKER_BROCK, 3
	famechecker FAMECHECKER_BROCK, 4
	famechecker FAMECHECKER_BROCK, 5
	famechecker FAMECHECKER_MISTY, 0
	famechecker FAMECHECKER_MISTY, 1
	famechecker FAMECHECKER_MISTY, 2
	famechecker FAMECHECKER_MISTY, 3
	famechecker FAMECHECKER_MISTY, 4
	famechecker FAMECHECKER_MISTY, 5
	famechecker FAMECHECKER_LTSURGE, 0
	famechecker FAMECHECKER_LTSURGE, 1
	famechecker FAMECHECKER_LTSURGE, 2
	famechecker FAMECHECKER_LTSURGE, 3
	famechecker FAMECHECKER_LTSURGE, 4
	famechecker FAMECHECKER_LTSURGE, 5
	famechecker FAMECHECKER_ERIKA, 0
	famechecker FAMECHECKER_ERIKA, 1
	famechecker FAMECHECKER_ERIKA, 2
	famechecker FAMECHECKER_ERIKA, 3
	famechecker FAMECHECKER_ERIKA, 4
	famechecker FAMECHECKER_ERIKA, 5
	famechecker FAMECHECKER_KOGA, 0
	famechecker FAMECHECKER_KOGA, 1
	famechecker FAMECHECKER_KOGA, 2
	famechecker FAMECHECKER_KOGA, 3
	famechecker FAMECHECKER_KOGA, 4
	famechecker FAMECHECKER_KOGA, 5
	famechecker FAMECHECKER_SABRINA, 0
	famechecker FAMECHECKER_SABRINA, 1
	famechecker FAMECHECKER_SABRINA, 2
	famechecker FAMECHECKER_SABRINA, 3
	famechecker FAMECHECKER_SABRINA, 4
	famechecker FAMECHECKER_SABRINA, 5
	famechecker FAMECHECKER_BLAINE, 0
	famechecker FAMECHECKER_BLAINE, 1
	famechecker FAMECHECKER_BLAINE, 2
	famechecker FAMECHECKER_BLAINE, 3
	famechecker FAMECHECKER_BLAINE, 4
	famechecker FAMECHECKER_BLAINE, 5
	end